# Generated by Django 4.2.6 on 2023-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile_number',
            field=models.IntegerField(max_length=14),
        ),
    ]
