# Generated by Django 4.2.6 on 2023-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
